name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - name: Install theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

      - name: Build
        run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
